# File: docker-compose.yml
# Author: Marc Bria UAB (marc.bria@uab.es)

services:
  db:
    image: mariadb:10.2
    env_file:
      - .env
    container_name: "pkp_db_${COMPOSE_PROJECT_NAME:-demo}"
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD:-pkpPwd}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-pkp}"
      MYSQL_USER: "${MYSQL_USER:-pkp}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD:-pkpPwd}"
    volumes:
      - ./volumes/db:/var/lib/mysql
      - ./volumes/logs/db:/var/log/mysql
      - ./volumes/config/db.charset.conf:/etc/mysql/conf.d/charset.cnf
      - ./volumes/migration:/docker-entrypoint-initdb.d
    networks:
      - inside
    restart: always

  app:
    image: local/${PKP_TOOL}:3_3_0-17
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env      
    #container_name: "${CONTAINER_NAME}"
    container_name: "pkp_app_${COMPOSE_PROJECT_NAME:-demo}"
    hostname: "${COMPOSE_PROJECT_NAME:-demo}"
    ports:
      - "${HTTP_PORT:-8081}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      # Keep host and container sync:
      - /etc/localtime:/etc/localtime
      # Monta el script en el contenedor
#      - ./copy-plugins-script.sh:/usr/local/bin/copy_from_container.sh
#      - ./volumes/private:/var/www/files
#      - ./volumes/public:/var/www/html/public
#      - ./volumes/logs/app:/var/log/apache2
#      # WARNING: You can only enable file-volumes if file exists in the container.
      - ./volumes/config/config.inc.php:/var/www/html/config.inc.php
      - ./volumes/config/apache.htaccess:/var/www/html/.htaccess
      - ./volumes/config/php.custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./volumes/plugins:/var/www/html/plugins
    #command: /bin/bash -c "/usr/local/bin/copy-plugins-script.sh ${CONTAINER_NAME} ./volumes/plugins"

    networks:
      - inside
    depends_on:
      - db
    restart: always

networks:
  inside:  
    external: false
